@startuml
node "Smartphone"
node "Serveur"
[App_Name]
[REST API]
[Linux Debian Wheezy 7.8]
[Linux Kernel V4.1.7]
[MySQL]
[Android V4.0.3]
interface "HTTPS"

[App_Name] ..> Smartphone
[Android V4.0.3] ..> Smartphone
Smartphone -> HTTPS
HTTPS --> [REST API]
[REST API] ..> Serveur
[MySQL] ..> Serveur
[Linux Kernel V4.1.7] ..> Serveur
[Linux Debian Wheezy 7.8] ..> Serveur

@enduml