@startuml
node "Telephone"
node "Serveur"
[App_Name]
[REST API]
[MySQL]
[Android VX.X.X]
interface "HTTPS"

[App_Name] ..> Telephone
[Android VX.X.X] ..> Telephone
Telephone -> HTTPS
HTTPS --> [REST API]
[REST API] ..> Serveur
[MySQL] ..> Serveur

@enduml