@startuml
node "Smartphone"
node "Serveur"
[App_Name]
[REST API]
[Linux Debian Wheezy]
[MySQL]
[Android VX.X.X]
interface "HTTPS"

[App_Name] ..> Smartphone
[Android VX.X.X] ..> Smartphone
Smartphone -> HTTPS
HTTPS --> [REST API]
[REST API] ..> Serveur
[MySQL] ..> Serveur
[Linux Debian Wheezy] ..> Serveur

@enduml